Feature/jc 521 book app layout
saritasa-nest/camp-js-2023-emil-arzumanov pull request #1
Opened 2023-07-07 06:18 UTC by Emil-Arzumanov

2023-07-07 08:22 UTC, khoanguyen-saritasa requested changes
Well done, the layout seems to be completed. But let's improve your code styles a little bit:
- I see you named your class randomly, with no specific rules. This might lead to difficulties in the maintenance and refactoring process and decreased reusability and modularity of components. Since you are coding in Vanilla, without any framework (which means your css file might not be modularized), it will increase the risk of naming collisions. Therefore, let's stick the class naming rules to [BEM](https://en.bem.info/methodology/) method. You can view it on [our wiki](https://wiki.saritasa.rocks/frontend/languages/css/#bem) also.
- Let's improve the schematics of your HTML structure. I don't see your `main` tag in the page. A page should contain `main` tag, which will hold your main content of the page, and it should be between `header` and `footer` tags. 
- I see there is a warning with SonarCloud. Can you fix it also?

2023-07-07 08:22 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/1/index.css
> +}
Let's move your variable to another specific file. That way, we can reuse them in another location if needed.

2023-07-07 08:22 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/1/index.css
> +}
And move those to another CSS file also to improve the readability and explicitness of it functionality. For example: `reset.css`

2023-07-07 08:22 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/1/index.css
> +  font-size: 20px;
Let use `rem` for the font size unit. `rem` units help maintain accessibility by allowing users to adjust the base font size in their browser settings. Users with visual impairments or specific font size preferences can increase or decrease the font size, and the entire page will respond accordingly.

2023-07-07 08:22 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/1/index.css
> +  width: 167.2px;
Don't be too precise :) You can refer [our wiki](https://wiki.saritasa.rocks/frontend/languages/css/#dont-be-too-precise) for the reason.

2023-07-07 08:22 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/1/index.css
> +    width: 172.5px;
Same precise issue.

2023-07-07 08:22 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/1/index.css
> +    grid-template-columns: 1fr 1fr 1fr;
```suggestion
    grid-template-columns: repeat(3,1fr);
```

2023-07-07 08:22 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/1/index.css
> +
Let's move it to another css component file, for example: dropdown.css

2023-07-07 08:22 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/1/index.css
> +  font-size: 20px;
Same issue with `font-size`

2023-07-07 08:22 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/1/index.css
> +}
Let move it to another file also for checkbox.

2023-07-07 08:22 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/1/index.css
> +  font-size: 20px;
font-size issue.

2023-07-07 08:22 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/1/index.css
> +  font-size: 20px;
font-size issue.

2023-07-07 08:22 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/1/index.css
> +  --surface: #fff;
Let's name our variable more explicit. For example: --primary-color, --border-color, --primary-text-color, ... Because we might have many variables and properties related to border or text.

2023-07-07 08:34 UTC, khoanguyen-saritasa commented
Seem like there is an issue with spacing between filters on the mobile screen. They are sticking to each other. Can you fix it also?
![image](https://github.com/saritasa-nest/camp-js-2023-emil-arzumanov/assets/108647361/2905d387-1d41-472e-a13c-91a16eb6fb3e)

2023-07-07 08:39 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/1/index.css
> +  --surface: #fff;
Our wiki also has a section for css variable naming, please take a look into it. https://wiki.saritasa.rocks/frontend/languages/css/#naming

2023-07-07 10:43 UTC, golovachev-yaroslav requested changes

2023-07-07 10:43 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/1/reset.css
> +* {
I think it would be better to use normalize.css
https://necolas.github.io/normalize.css/

2023-07-07 10:43 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/1/index.html
>            <section class="books_one_category">
Section in section looks strange. I think section > div is much better here.

2023-07-07 10:43 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/1/index.html
>          <h1 class="header__h1">📚 Books app</h1>
What if you change tag `h1` to `h2`?
`<h2 class="header__h1">📚 Books app</h2>` will looks strange. It would be better to give a name independent of the tag name.
`<h2 class="header__heading">📚 Books app</h2>`
or
`<h2 class="header__text-header">📚 Books app</h2>`
or something like this.

2023-07-10 03:20 UTC, khoanguyen-saritasa requested changes
Please revise your BEM structure. This is the syntax of BEM that we usually use: `block__element_modifier`.

2023-07-10 03:20 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/1/index.html
> +      <main class="main_catalog">
For example in this case, the name of the wrapper section class should be `main-section`. And the name of header class should be `main-section__header`. If you want to add another block, or rename it since the name is too long, you should place your alternative name right after that wrapper block first, and then use it like the other class. In summary, you should change your class names to something like this: 
```suggestion
    <section class="main-section">
      <header class="main-section__header header">
        <h1 class="header__heading">📚 Books app</h1>
      </header>
      <main class="main_catalog">
```

2023-07-10 06:06 UTC, golovachev-yaroslav requested changes

2023-07-10 06:06 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/1/css/dropdown-select.css
> +.select::after {
`::after,` `::before` does not work with `img`, `input`, `select`
https://qna.habr.com/q/193821

2023-07-10 06:06 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/1/css/index.css
> +  outline: 1px solid #0000001a;
PLease use a variable.

2023-07-10 06:06 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/1/css/index.css
> +@media screen and (max-width: 880px) and (min-width: 596px) {
It would be better to write from min to max
`@media screen and (min-width: 596px) and (max-width: 880px) {`

2023-07-10 06:06 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/1/index.html
> +              <section class="books_one_category__book">
Too many section inside section
http://htmlbook.ru/html/section

2023-07-10 10:12 UTC, Emil-Arzumanov commented on apps/vanilla/src/pages/1/index.html
> +      <main class="main_catalog">
Thank you for review! Pavel said not to bother too much about BEM, because we are moving fast, and the task may take too long. But I still rewrote the styles for the header and footer a little, trying to do it according to BEM.

2023-07-11 07:53 UTC, khoanguyen-saritasa approved these changes
Well done, keep it up.

2023-07-12 08:01 UTC, pavel-romanov8 requested changes
I noticed the next problems with the current state of the app:

- Smashed placeholder of the select. Would be great to provide left padding to it
<img width="311" alt="Screenshot 2023-07-12 at 13 36 58" src="https://github.com/saritasa-nest/camp-js-2023-emil-arzumanov/assets/82144989/2805bb84-8d31-407f-94a9-441b096a7226">

- Sticky year elements doesn't have enough space while scrolling (gray area on screenshot is the top bar of the browser)
<img width="476" alt="Screenshot 2023-07-12 at 13 37 21" src="https://github.com/saritasa-nest/camp-js-2023-emil-arzumanov/assets/82144989/70ea3732-0f31-49c4-a3b9-d61c70b2fe3e">

2023-07-12 08:09 UTC, golovachev-yaroslav approved these changes

2023-07-13 02:43 UTC, viktor-sakhno-saritasa requested changes

2023-07-13 02:43 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/1/css/checkbox.css
> +  align-self: stretch;
Do we really need to set `align-self` here? As I remember, `stretch` is the default value for this property.

2023-07-13 02:43 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/1/css/checkbox.css
> +  }
If you fix above comment, we can avoid this code and set `align-items: center` for `filter__filter-inputs`. We stick the way, when parent block manages position of children. In your case, your checkbox decides how to stand inside the parent. Check section in our [wiki](https://wiki.saritasa.rocks/frontend/languages/css#componentselements-should-not-position-themselves), pls.

2023-07-13 02:43 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/1/css/index.css
> +@media screen and (max-width: 880px) {
Why do we need to specify `screen` anywhere? Usually, it allows overriding styles for other type of devices: `print`, for example. But, as I understand, we will not write styles for printers, so it doesn't need. 

BTW, I see you use `and` to combine queries. It would be great to use new media queries range syntax. It accesses in all modern browsers, and It allows to "read" media queries (but that's subjective I guess). 

So you can rewrite this `@media screen and (min-width: 596px) and (max-width: 880px)` to this `@media (596px <= width <= 880px)`

2023-07-13 02:43 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/1/css/index.css
> +}
Why do we need to hide scrollbar? It is bad UX, I believe. What if the user broke his mouse wheel?

2023-07-13 02:43 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/1/css/index.css
> +  margin-bottom: 24px;
The same as above, about self-positioning of elements.

2023-07-13 02:43 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/1/css/index.css
> +  z-index: 1;
Usually, we're trying to write comments, why we use `z-index`, if we really need it. Check [wiki](https://wiki.saritasa.rocks/frontend/languages/css#explain-why-tricks-are-used-z-index-important), pls.

2023-07-13 02:43 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/1/css/index.css
> +.footer__data {
Try to avoid such abstract words like `data` in this case. What type of data here?

2023-07-13 02:43 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/1/index.html
> +            <header class="books-category__header">
I don't see `books-category` block above, only an element of `books` block.

2023-07-13 02:43 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/1/index.html
> +                <div class="books-category__image-wrapper">
If we are trying to be semantic, I think we can to improve this place and replace at lease on `div` tag on suitable semantic tag? I see only `wrapper` here can be `div`. What do you think?

2023-07-13 02:43 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/1/index.html
> +                <div>Yokohama Kaidashi Kikou</div>
Why do you wrap usual plain text in `div`?

2023-07-13 02:43 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/1/index.html
> +            <span>© 2023</span>
We prefer to use [HTML entities](https://www.w3schools.com/html/html_entities.asp#:~:text=%C2%A9-,copyright,-%26copy%3B) for such symbols.

2023-07-13 09:22 UTC, Emil-Arzumanov commented on .editorconfig
> +indent_style = space
stylelintrc complains in '.css' files about tabs: "Expected indentation of 2 spaces (indentation)Stylelint[indentation]". Currently I changed config, so that 'space' will only be in '.css' files.

2023-07-13 09:45 UTC, Emil-Arzumanov commented on apps/vanilla/src/pages/1/index.html
> +    <section class="main-section">
Thanks for the review! It's just a matter of personal preference, I'd like to leave it as it is. But of course, if it's considered to be a bad practice, I'll change it.

2023-07-13 09:53 UTC, Emil-Arzumanov commented on apps/vanilla/src/pages/1/index.html
> +    <section class="main-section">
I wan't to leave this wrapper, but maybe a should change 'section' to 'div'?

2023-07-13 12:23 UTC, Emil-Arzumanov commented on apps/vanilla/src/pages/1/index.html
> +                <div class="books-category__image-wrapper">
I talked about this with Yaroslav. He said that the nesting of one section into another should not exceed 2. He also suggested me to to name all these tags as 'div'. But I think element with class "books-category__book" should be section.

2023-07-13 17:29 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/1/css/index.css
> +  margin-bottom: 24px;
I didn't see real reasons to not use `gap`. It supports all modern browsers and work perfectly. If you use BEM, children element shouldn't set your position himself, it breaks BEM approach logic. I believe if all children elements will set your position himself, soon it will be a mess, where it will not be clear who, why and how is positioned.

2023-07-13 17:32 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/1/index.html
> +                <div class="books-category__image-wrapper">
I think `books-category__book` it is an independent piece of information. So it could be `article`, for example.

2023-07-14 06:19 UTC, golovachev-yaroslav approved these changes

2023-07-14 06:19 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/1/index.html
>  										<source media="(min-width: 881px)" srcset="./imgs/desktop/image1.png" />
881 is not standard width. Maybe 768?
https://gist.github.com/gokulkrishh/242e68d1ee94ad05f488

2023-07-17 04:37 UTC, viktor-sakhno-saritasa approved these changes

2023-07-17 05:11 UTC, Emil-Arzumanov commented on apps/vanilla/src/pages/1/index.html
>  										<source media="(min-width: 881px)" srcset="./imgs/desktop/image1.png" />
I had to slightly change the screen width for the tablet version, as the design did not adapt well to the smaller screen width.

2023-07-17 05:13 UTC, merged