Feature/jc 532 blackjack by dice
saritasa-nest/camp-js-2023-emil-arzumanov pull request #2
Opened 2023-07-12 14:03 UTC by Emil-Arzumanov

2023-07-12 23:24 UTC, viktor-sakhno-saritasa commented
@Emil-Arzumanov, hi, could you change base branch to merge, pls. Set branch from previos PR #1  instead `develop`, to see only new changes. Sometimes, we checkout new branch from another branch to get some useful peaces of code or just to avoid merge conflicts, but I recommend to set the branch from which you made checkout as the base branch where you want to merge your changes. Then, after approve, you can change it and set `develop` again.

2023-07-13 03:33 UTC, viktor-sakhno-saritasa requested changes

2023-07-13 03:33 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/2/logick/publisher.ts
> +	public constructor() {}
Remove empty constructor.

2023-07-13 03:33 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/2/logick/publisher.ts
> +/* eslint-disable jsdoc/require-jsdoc */
Don't disable ESLint rules without value reason.

2023-07-13 03:33 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/2/logick/publisher.ts
> +	private readonly subscribers: Subscriber<T>[] = [];
We also can add `readonly` for array, not only for property.
```suggestion
	private readonly subscribers: readonly Subscriber<T>[] = [];
```

2023-07-13 03:33 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/2/logick/diceGenerator.ts
> +		this.diceRollResult = Math.floor(Math.random() * (max + 1 - min) + min);
Why do we need to save the result in the variable? I believe we can just return generated number from this function.

2023-07-13 03:33 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/2/logick/index.ts
> +	private turnGenerator: TurnGenerator;
Don't forget about `readonly`.
```suggestion
	private readonly turnGenerator: TurnGenerator;
```

2023-07-13 04:17 UTC, AndreySkripachev approved these changes

2023-07-13 04:17 UTC, AndreySkripachev commented on apps/vanilla/src/pages/2/index.css
> +.game div p {
Using tag names to describe styles is bad practice. A better practice would be to use BEMIt is bad practice to use tag names to describe styles

2023-07-13 04:17 UTC, AndreySkripachev commented on apps/vanilla/src/pages/2/logick/player.ts
> +	 * @param score Array of dice roll results.
As far as I know, `@param` is used to describe function parameters. Correct me if I am wrong

2023-07-13 04:17 UTC, AndreySkripachev commented on apps/vanilla/src/pages/2/logick/publisher.ts
> +		this.subscribers.forEach((sub: Subscriber<T>) => sub.update(data));
You don't have to use type annotation for callback function parameters. TypeScript does this automatically

2023-07-13 04:17 UTC, AndreySkripachev commented on apps/vanilla/src/pages/2/logick/player.ts
> +	 * @param diceRollResult Result of dice roll made in current turn.
As I see it, you've described parameters that don't exist

2023-07-13 04:17 UTC, AndreySkripachev commented on apps/vanilla/src/pages/2/logick/player.ts
> +	 * @param diceRollResult Result of dice roll made in current turn.
I saw that you were describing the parameter fields. Usually we document object fields in the interface

2023-07-13 05:14 UTC, Emil-Arzumanov commented on apps/vanilla/src/pages/2/logick/publisher.ts
> +	public constructor() {}
Hi! I did it because eslint tells me: "Expected blank line between class members."

2023-07-13 07:49 UTC, khoanguyen-saritasa approved these changes

2023-07-13 07:49 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/2/logick/publisher.ts
> +	public constructor() {}
I don't see the relevance in your mentioned eslint warning and removing empty constructor. Are you sure about it? @Emil-Arzumanov

2023-07-13 17:38 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/2/logick/publisher.ts
> +	public constructor() {}
So, just make an empty line between class members. You don't need to add constructor for this purpose)

2023-07-13 17:42 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/2/logick/diceGenerator.ts
> +		this.diceRollResult = Math.floor(Math.random() * (max + 1 - min) + min);
I didn't see your changes for this). I mean you can do instead of this:
`this.diceRollResult = Math.floor(Math.random() * (max + 1 - min) + min);`

this: `return Math.floor(Math.random() * (max + 1 - min) + min);` and then you don't need a variable. You just can write `this.notify({ diceRollResult: this.throwDice(1, 6), currentPlayerIndex });`

2023-07-17 04:44 UTC, viktor-sakhno-saritasa requested changes

2023-07-17 04:44 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/2/index.html
> +    <script type="module" src="./logick/index.ts"></script>
Did you mean `logic`?

2023-07-17 04:44 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/2/logick/diceGenerator.ts
> +		this.diceRollResult = Math.floor(Math.random() * (max + 1 - min) + min);
Usually, we don't resolve the issue, when it wasn't fixed. If you have problems with that, you can write me.

2023-07-17 04:44 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/2/logick/player.ts
> +	private diceRollResults: number[] = [];
```suggestion
	private readonly diceRollResults: readonly number[] = [];
```

2023-07-17 04:44 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/2/logick/player.ts
> +		}
```suggestion
		this.winStatus = this.score >= 21;
```

Usually, we didn't change property directly, let's go make our functions pure, when function just return a value.

2023-07-17 04:44 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/2/logick/publisher.ts
> +		if (subscriberIndex === -1 && Array.isArray(this.subscribers)) {
Why do we need this checking `Array.isArray(this.subscribers)` as I see, it always is array.

2023-07-17 04:44 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/2/logick/resultDisplay.ts
> +	private app = document.getElementById('game');
```suggestion
	private readonly app = document.getElementById('game');
```
Please, revise all your property to add `readonly` where it is possible.

2023-07-17 06:47 UTC, viktor-sakhno-saritasa approved these changes

2023-07-17 06:47 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/2/logic/diceGenerator.ts
> +		this.notify({ diceRollResult: this.diceRollResult, currentPlayerIndex });
Ok, it is good, but we can do next step and remove redundant property from the class.
```suggestion
		this.notify({ diceRollResult: this.throwDice(1, 6), currentPlayerIndex });
```

2023-07-17 08:39 UTC, merged