Feature/jc 539 initialize anime app and table view angular
saritasa-nest/camp-js-2023-emil-arzumanov pull request #3
Opened 2023-07-19 09:43 UTC by Emil-Arzumanov

2023-07-20 03:52 UTC, viktor-sakhno-saritasa requested changes

2023-07-20 03:52 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/app-routing.module.ts
> +];
Hi. A well-functioning application should gracefully handle when users attempt to navigate to a part of your application that does not exist. To add this functionality to your application, you set up a [wildcard route](https://angular.io/guide/router#setting-up-wildcard-routes).

2023-07-20 03:52 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/table/table.component.css
> +.image-wrapper img {
Please, use BEM.

2023-07-20 03:52 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/table/table.component.html
> +	<div>
Why do we need this two extra `div`?

2023-07-20 03:52 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/table/table.component.css
> +  transform: translate(-50%, -50%);
Why do we need to position our images absolute?

2023-07-20 03:52 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +	public displayedColumns: string[] = ['image', 'titleEng', 'titleJpn', 'airedStart', 'type', 'status'];
We prefer to encapsulate class properties as possible. So I suggest replacing `public` modifier to just `protected` instead. 
```suggestion
})
export class TableComponent implements OnInit {
	/** Columns of table to display. */
	protected readonly displayedColumns: readonly string[] = ['image', 'titleEng', 'titleJpn', 'airedStart', 'type', 'status'];
```

2023-07-20 03:52 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +	public animeList: readonly Anime[] = [];
Don't forget about `readonly` modifier.

2023-07-20 03:52 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +	/** A function that is triggered when a component is initialized. */
```suggestion
	/** @inheritdoc */
```

2023-07-20 03:52 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +		this.animeService.getAnimeList().subscribe((data): void => {
Don't forget about managing your subscriptions. If you `subscribe` anywhere, make sure that you don't forget to unsubscribe before component destroying. We have a special lifecycle hook for this, like `ngOnInit`, only `ngOnDestroy`.

2023-07-20 03:52 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +			this.animeList = data.results;
Ok, I see you don't use `Observable` now. I think you can stay so, but be ready, after lection about `Change Detection`, you will face with problems, and we will need to rewrite some things :)

2023-07-20 03:52 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/interceptors/anime.interceptor.ts
> +export class AnimeInterceptor<T> implements HttpInterceptor {
I think is not `Anime` but `AuthInterceptor`, what do you think?

2023-07-20 03:52 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +	private offset = '25';
Usually, we move out constants above class declaration and use upper case snake case for constants like `const OFFSET = '25'`;

2023-07-20 03:52 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +	public constructor(private http: HttpClient) {}
```suggestion
	public constructor(
	  private readonly http: HttpClient
	) { }
```

2023-07-20 03:52 UTC, viktor-sakhno-saritasa commented on apps/angular/src/index.html
> +      <link rel="preconnect" href="https://fonts.gstatic.com">
Formatting.

2023-07-20 04:35 UTC, AndreySkripachev requested changes

2023-07-20 04:35 UTC, AndreySkripachev commented on apps/angular/src/app/features/anime/table/table.component.html
> +					<img [src]="row.image" alt="Anime image" />
"Anime image" is not the most meaningful title. It would be better to use something like "Poster" or write the name of the anime in the alt attribute

2023-07-20 04:35 UTC, AndreySkripachev commented on apps/angular/src/app/features/anime/table/table.component.html
> +		<mat-paginator [length]="100" [pageSize]="5" [pageSizeOptions]="[25, 50, 100, 200]" aria-label="Select page">
Why did you comment that?

2023-07-20 04:35 UTC, AndreySkripachev commented on apps/angular/src/core/services/anime.service.ts
> +					(elem: PaginationDto<AnimeDto>): Pagination<Anime> =>
There is no need to specify types in callback functions. TypeScript does this automatically.

2023-07-20 04:35 UTC, AndreySkripachev commented on libs/core/dtos/pagination.dto.ts
> +export interface PaginationDto<DTO> {
Why did you change the name of the generic? Even if you want to change it, something like `TDto` or just `T` is probably a better option

2023-07-20 04:35 UTC, AndreySkripachev commented on libs/core/mappers/anime.mapper.ts
> +import { Anime } from './../models/anime';
```suggestion
import { Anime } from '../models/anime';
```

2023-07-20 04:35 UTC, AndreySkripachev commented on libs/core/mappers/pagination.mapper.ts
> +	export function fromDto<DTO, MODEL>(dto: PaginationDto<DTO>, mapper: (dto: DTO) => MODEL): Pagination<MODEL> {
We typically define generic names in CamelCase format

2023-07-20 04:35 UTC, AndreySkripachev commented on libs/core/models/anime.ts
> +	public readonly type: string;
As I see it, the api can send us a limited number of anime types. For example OVA, Movie, Special, etc. In this case, a good solution is to reduce the string type to the values that api can send us. This can be done by creating an enum or type that contains all possible values

2023-07-20 04:35 UTC, AndreySkripachev commented on libs/core/models/anime.ts
> +	public readonly status: string;
Same thing about status

2023-07-20 06:04 UTC, Emil-Arzumanov commented on apps/angular/src/app/features/anime/table/table.component.ts
> +	public animeList: readonly Anime[] = [];
But why it should be 'readonly'? I have method "getAnimeList" that assigns data to it.

2023-07-20 07:49 UTC, Emil-Arzumanov commented on apps/angular/src/core/interceptors/anime.interceptor.ts
> +export class AnimeInterceptor<T> implements HttpInterceptor {
This interceptor only adds an 'Api-Key' to request header. So i decided to name it 'ApiKeyInterceptor' and import it into 'app.module' instead of 'anime.module', because I will probably need it in the whole application.

2023-07-20 09:38 UTC, khoanguyen-saritasa requested changes

2023-07-20 09:38 UTC, khoanguyen-saritasa commented on apps/angular/src/shared/components/page-not-found/page-not-found.component.html
> +</div>
It should be `error` first and `error__wrapper` come after if you are sticking to BEM method.

2023-07-20 09:38 UTC, khoanguyen-saritasa commented on apps/angular/src/shared/shared.module.ts
> +	declarations: [PageNotFoundComponent, PageNotFoundComponent],
Duplicate component declarations.

2023-07-20 09:38 UTC, khoanguyen-saritasa commented on libs/core/models/pagination.ts
> +export class Pagination<MODEL> extends Immerable {
```suggestion
export class Pagination<TModel> extends Immerable {
```

2023-07-20 09:38 UTC, khoanguyen-saritasa commented on apps/angular/src/core/interceptors/anime.interceptor.ts
> +				'Api-Key': '9c9da0d3-c65c-402b-8df6-4a04ad9fa847',
Please declare the API key in `environment.ts` file of the Angular app. This is an environment variable and should not be hard-coded in this layer.

2023-07-20 09:38 UTC, khoanguyen-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +	private readonly animeURL = 'https://api.camp-js.saritasa.rocks/api/v1/anime/anime/';
I think you should create a service and utilities needed for constructing the API URL since `https://api.camp-js.saritasa.rocks/api/v1/` is the base URL, it will be used across the application. If you hard-code here, when it changed, you need to fix every request to the API.

2023-07-20 09:38 UTC, khoanguyen-saritasa commented on libs/core/dtos/anime.dto.ts
> +	readonly id: number;
You can omit the text which includes `of this anime` or `this anime` since it's obvious that all properties defined in the DTO belong to that DTO. Please update the docs for the rest also.

2023-07-20 11:07 UTC, Emil-Arzumanov commented on apps/angular/src/core/services/anime.service.ts
> +	private readonly animeURL = 'https://api.camp-js.saritasa.rocks/api/v1/anime/anime/';
I created 'url-config.service' to construct URLs, but didn't create any utilities, because i don't where to use them wright know. Maybe i will need them later, when app will get bigger? Could you explain, please?

2023-07-20 11:27 UTC, Emil-Arzumanov commented on apps/angular/src/core/services/anime.service.ts
> +	private offset = '25';
I was just playing with request 'params'. I will work with pagination for table in separate branch, because its different task.

2023-07-21 07:16 UTC, AndreySkripachev requested changes

2023-07-21 07:16 UTC, AndreySkripachev commented on apps/angular/src/app/app.module.ts
>  import { SharedModule } from './../shared/shared.module';
```suggestion
import { SharedModule } from '../shared/shared.module';
```

2023-07-21 07:16 UTC, AndreySkripachev commented on libs/core/dtos/airedDate.dto.ts
I notice you're using different file naming styles. Please stick to one naming style

2023-07-21 08:54 UTC, khoanguyen-saritasa approved these changes

2023-07-21 08:54 UTC, khoanguyen-saritasa commented on apps/angular/src/core/services/url-config.service.ts
> +	}
```suggestion
	public toApi(...args: readonly string[]): string {
		const path = args.join('/');
		const concatenatedUrl = new URL(path, this.baseUrl).toString()
		return `${concatenatedUrl}/`;
	}
```

2023-07-21 08:54 UTC, khoanguyen-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +	private readonly animeListUrl = this.appUrlsConfig.toApi('anime/', 'anime/');
With the update of `toApi` function, you can simplify your args to `this.appUrlsConfig.toApi('anime', 'anime')` without `/` suffix of each path.

2023-07-21 08:54 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +	protected animeList$: Observable<Pagination<Anime>>;
```suggestion
	protected readonly animeList$: Observable<Pagination<Anime>>;
```

2023-07-21 10:47 UTC, timofei-maximov-saritasa requested changes

2023-07-21 10:47 UTC, timofei-maximov-saritasa commented on libs/core/dtos/anime.dto.ts
> +export enum AnimeTypesDto {
Usually we use a singular noun names for types.

```suggestion
export enum AnimeTypeDto {
```

2023-07-21 10:47 UTC, timofei-maximov-saritasa commented on libs/core/dtos/airedDate.dto.ts
> +	/** Date when anime was first aired. */
It is a good practice to specify date format in docs. Sometimes we need to know a format to create a date instance using date libraries like `luxon`

2023-07-21 10:47 UTC, timofei-maximov-saritasa commented on libs/core/dtos/anime.dto.ts
> +	/** Status. Is it aired, finished, or net aired yet. */
No need here to specify all values in docs.

2023-07-21 10:47 UTC, timofei-maximov-saritasa commented on libs/core/mappers/anime.mapper.ts
> +			modified: dto.modified,
According to your docs: 
> 	/** Date of last updated in DB. */

But here you have datestring, lets fix it

2023-07-21 10:47 UTC, timofei-maximov-saritasa commented on libs/core/dtos/anime.dto.ts
> +	/** Date of creation in DB. */
We don't have such knowledge about DB. This date can be set by us when we send a new item to the server. 
Let's improve docstring

2023-07-21 10:47 UTC, timofei-maximov-saritasa commented on libs/core/models/anime.ts
> +	public readonly image: string;
`image` can be confusing. Let's rename it to `imageUrl`

2023-07-21 10:47 UTC, timofei-maximov-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +	 * @param limit Maximum of results to return.
You don't have these params. Either add them or delete these docs

2023-07-21 10:47 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +	}
Can't we use `this.animeService.getAnimeList()` directly?

2023-07-21 10:47 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +	public constructor(private animeService: AnimeService) {
```suggestion
	public constructor(private readonly animeService: AnimeService) {
```

If you are not planning to use `animeService` outside of constructor, then you can omit `private` modifier.

```suggestion
	public constructor(animeService: AnimeService) {
```

____

Also, we can use `inject` from angular instead of injecting into constructor. This is recommended way to inject dependencies

```ts
export class TableComponent {
  private readonly animeService = inject(AnimeService);
  
  // other code ...
}
```

2023-07-24 01:37 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime.module.ts
> +	imports: [CommonModule, HttpClientModule, MatTableModule, DatePipe, MatPaginatorModule],
Is it required to put `DatePipe` into `imports` list? As far as I remember it's in `exports` section of the `CommonModule` so we don't need to import it manually

2023-07-24 01:37 UTC, dbitkovski commented on apps/angular/src/core/interceptors/anime.interceptor.ts
> +/** Interceptor for AnimeService. */
Won't you be able to apply this interceptor to any other service except `AnimeService`? I think we need to improve docs

2023-07-24 01:37 UTC, dbitkovski commented on apps/angular/src/core/interceptors/anime.interceptor.ts
> +	 */
Use `@inheritdoc` instead, it's enough here. You can explain what this interceptor stands for in class documentation

2023-07-24 01:37 UTC, dbitkovski commented on apps/vanilla/src/pages/1/css/variables.css
> +  --input-background-color: #f2f2f2;
Be consistent. Use one notation to express colors

2023-07-24 02:38 UTC, AndreySkripachev approved these changes

2023-07-24 05:04 UTC, viktor-sakhno-saritasa approved these changes

2023-07-24 05:04 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/1/css/index.css
> +  opacity: 1; /* Firefox */
If you leave such comments, please, make it more clear. You could improve this comment and add additional information, about what actually happens in the Firefox browser.

2023-07-24 05:23 UTC, timofei-maximov-saritasa approved these changes
![image](https://github.com/saritasa-nest/camp-js-2023-emil-arzumanov/assets/86595911/5bba2c7a-156f-4f2c-8c6f-be4a1b459056)

There is something wrong with titles. Can you check what you get from the API?

2023-07-24 05:48 UTC, merged

2023-07-24 06:43 UTC, pavelzadorin-saritasa approved these changes

2023-07-24 06:43 UTC, pavelzadorin-saritasa commented on libs/core/models/pagination.ts
> +	/** Amount of anime in DB. */
pagination is a generic class that is not related to `Anime`, respectively, and there should not be this relation in the comments.