Feature/jc 545 anime list management
saritasa-nest/camp-js-2023-emil-arzumanov pull request #5
Opened 2023-07-26 10:45 UTC by Emil-Arzumanov

[TASK]( https://saritasa.atlassian.net/jira/software/c/projects/JC/boards/484?modal=detail&selectedIssue=JC-542)

2023-07-26 12:17 UTC, golovachev-yaroslav approved these changes

2023-07-26 15:45 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/app/features/anime/table/table.component.html
> +		<input matInput placeholder="Ex. One Punch Man" [formControl]="filterForm.controls.search" />
You can use just `formControlName` for controls inside form group.

```suggestion
		<input matInput placeholder="Ex. One Punch Man" formControlName="search" />
```

2023-07-26 15:45 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +	/** List.  */
Update docs please.

2023-07-26 15:45 UTC, gevorg-gevorgyan-saritasa commented on libs/core/mappers/airedDate.mapper.ts
>  	export function fromDto(dto: AiredDateDto): AiredDate {
Wrong file name. Should be in `kebab-case`

2023-07-26 15:45 UTC, gevorg-gevorgyan-saritasa commented on libs/core/models/filter-params.ts
> +export class FilterParams {
Do you really need a `class` here? Maybe you can use `interface AnimeFilterParams`  , since in your case it does not have any additional logic, and is used only to name object type.

2023-07-27 01:05 UTC, gevorg-gevorgyan-saritasa reviewed
One more thing. Read our [commit style guide](https://wiki.saritasa.rocks/general/git#style-guide), and you don't need to actually put a name of the reviewer in your commit message. There is no need to make commit messages bigger adding such unnecessary and useless information

2023-07-27 02:53 UTC, andrey-gazzaev commented on libs/core/models/anime-params.ts
> +	pagination: PaginationParams;
```suggestion
	readonly pagination: PaginationParams;
```

2023-07-27 02:53 UTC, andrey-gazzaev commented on libs/core/models/filter-params.ts
> +	type: AnimeType[] | null;
```suggestion
	readonly type: readonly AnimeType[] | null;
```

2023-07-27 02:53 UTC, andrey-gazzaev commented on libs/core/models/sorting-params.ts
> +	activeField: ActiveField;
Can we find a better name for the sorting field?

2023-07-27 02:53 UTC, andrey-gazzaev commented on .vscode/settings.json
> +{
Do you really need that file?

2023-07-27 02:53 UTC, andrey-gazzaev commented on libs/core/mappers/filter-params.mapper.dto.ts
Looks like you have the wrong file name. Let's remove `dto` from the name

2023-07-27 02:53 UTC, andrey-gazzaev commented on libs/core/models/sorting-params.ts
>  /** All possible activeField values. */
Please check lint, it looks like you have case errors in `enum`.

2023-07-27 03:34 UTC, andrey-gazzaev requested changes

2023-07-27 03:34 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/table/table.component.html
> +		aria-describedby="anime list"
Don't forget to `use trackBy` for the table

2023-07-27 03:34 UTC, andrey-gazzaev commented on libs/core/mappers/sorting-params.mapper.ts
> +		const direction = model.direction === 'desc' ? '-' : '';
```suggestion
		const direction = model.direction === Direction.Descending ? '-' : '';
```
Let's use `Direction`

2023-07-27 03:34 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/table/table.component.ts
> +	public constructor(private fb: FormBuilder) {
Be consistent if you use `inject` then keep doing so or use a `constructor` instead of `inject`.

2023-07-27 03:34 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/table/table.component.ts
> +		if (snapshot['pageIndex'] && snapshot['pageSize']) {
```suggestion
		if (snapshot['pageIndex'] != null && snapshot['pageSize']  != null ) {
```

Avoid type casts.
What if you have a filter with a boolean value? Will this condition work the same way?

2023-07-27 03:34 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/table/table.component.ts
> +		this.sortingParams.activeField = event.active as ActiveField;
I dont think it is a good idea to typecast the UI model into the Domain model? Let's think about how to better map these models to each other.

2023-07-27 03:34 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/table/table.component.ts
> +		if (snapshot['activeField'] && snapshot['direction']) {
Let's come up with an enumeration for the keys of the snapshot object.

2023-07-27 03:34 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/table/table.component.ts
> +		const snapshot = this.route.snapshot.queryParams;
You can use `queryParamMap` to work with the query params stream. And shorten the code below

2023-07-27 04:05 UTC, daoduong-saritasa requested changes
Great job! Please, see my comments below.

2023-07-27 04:05 UTC, daoduong-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +		this.router.navigate([], { queryParams: { ...queryParams } });
Do we need to spread it?

2023-07-27 04:18 UTC, khoanguyen-saritasa requested changes

2023-07-27 04:18 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +			this.pagination$.next(this.paginationParams);
Why don't you modify directly `this.pagination$` but through an intermediate variable, which is `this.paginationParams`?  
```suggestion
			this.pagination$.next({pageIndex: snapshot['pageIndex'], pageSize: snapshot['pageSize']});
```

2023-07-27 04:18 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +		this.pagination$.next(this.paginationParams);
Same as above.

2023-07-27 04:18 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +	protected readonly pagination$ = new BehaviorSubject(this.paginationParams);
I'm not sure whether it's necessary to have both behavior subject `pagination$` and `paginationParams`. Can we leave  `paginationParams` and only work with our behavior subject `pagination$`?

2023-07-27 04:18 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +	protected readonly sorting$ = new BehaviorSubject(this.sortingParams);
The same with the behavior subject `sorting$`. Can we omit `sortingParams`?

2023-07-27 06:28 UTC, Emil-Arzumanov commented on libs/core/models/pagination-params.ts
> +	pageIndex: number;
Hello! Thank you for review! I use 'PaginatiosParams' interface for 'paginationParams' object in 'table.component.ts'. During the operation of the application, the values of 'pageSize' and 'pageIndex' change.

2023-07-27 19:35 UTC, Emil-Arzumanov commented on apps/angular/src/app/features/anime/table/table.component.ts
> +		const snapshot = this.route.snapshot.queryParams;
Hi, thanks for the review! So, for example with "queryParamMap", getting page index will look like this: "snapshot.get(Params.PageIndex)", instead of this: "snapshot[Params.PageIndex]". It doesn't seem to be much different, but of course I could have misunderstood you. Could you please explain why it is better to use "queryParamMap"

2023-07-28 03:23 UTC, khoanguyen-saritasa approved these changes

2023-07-28 03:25 UTC, daoduong-saritasa approved these changes

2023-07-28 03:53 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/table/table.component.ts
> +		const snapshot = this.route.snapshot.queryParams;
I must have misspoken, leave it as it is. Just know that there is a way to track changes to queryParams :)

2023-07-28 03:53 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +	public constructor() {}
Remove the empty constructor

2023-07-28 03:53 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +	 */
```suggestion
	/**
		* Sends get request to API and maps receives data.
	  * @param params Request parameters.
	  */
```

2023-07-28 03:53 UTC, andrey-gazzaev commented on libs/core/mappers/filter-params.mapper.ts
> +		const dtoType = model.type ? model.type.map(elem => AnimeMapper.ANIME_TYPES_TO_DTO[elem]).join(',') : '';
```suggestion
		const typeDto = model.type ? model.type.map(elem => AnimeMapper.ANIME_TYPES_TO_DTO[elem]).join(',') : '';
```

2023-07-28 03:53 UTC, andrey-gazzaev commented on libs/core/models/sorting-params.ts
> +	readonly activeSortField: SortField;
Let's keep it just `field`. No need to duplicate the context.

2023-07-28 03:53 UTC, andrey-gazzaev commented on libs/core/models/sorting-params.ts
> +export interface SortingParams {
```suggestion
export interface SortParams {
```

2023-07-28 03:53 UTC, andrey-gazzaev commented on libs/core/mappers/sorting-params.mapper.ts
> +const SORT_PARAMS_TO_DTO = {
In fact, such objects are also mappers.
```suggestion
const SORT_PARAMS_TO_DTO_MAP = {
```

2023-07-28 03:53 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/table/table.component.ts
> +			direction: event.direction !== '' ? event.direction as Direction : Direction.None,
It's not a good idea to cast the UI into the domain. If we do, we need to map one model to another.

Here is a clear example of a UI model that differs from a domain model. As I understand it, we don't need a third value in the sorting direction. That's why it would be a mistake to cast it

2023-07-28 03:53 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/table/table.component.ts
> +				})),
Let's unload this stream a bit and take `this.filterForm.valueChanges + pipe` to a separate variable. For example `filter$`.

2023-07-28 11:16 UTC, andrey-gazzaev commented on libs/core/models/sorting-params.ts
> +import { SortDirection } from '@angular/material/sort';
Why are you using a UI level data model in the domain level? It's a leaking abstraction. Why don't you write a mapper for this model?

2023-07-28 13:35 UTC, andrey-gazzaev approved these changes

2023-07-28 14:05 UTC, merged