Feature/jc 550 authorization
saritasa-nest/camp-js-2023-emil-arzumanov pull request #6
Opened 2023-08-02 11:24 UTC by Emil-Arzumanov

[TASK](https://saritasa.atlassian.net/browse/JC-548)

2023-08-02 11:44 UTC, golovachev-yaroslav requested changes

2023-08-02 11:44 UTC, golovachev-yaroslav commented on apps/angular/src/app/app-routing.module.ts
> +		loadChildren: () => import('./features/anime/anime.module').then(m => m.AnimeModule),
I think it would be better` .then(module => module.AnimeModule)`
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions

2023-08-02 11:44 UTC, golovachev-yaroslav commented on apps/angular/src/app/features/auth/login/login.component.ts
> +	private readonly fb = inject(FormBuilder);
Maybe `formBuilder` ?
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions

2023-08-02 11:44 UTC, golovachev-yaroslav commented on apps/angular/src/app/features/auth/login/login.component.ts
> +		let errorsArray: string[] = [];
Or you can do by this

```
const errorsArray: string[] = [];
...
errorsArray.push(Object.keys(formField.errors).map(error => formField.getError(error)));
```

2023-08-02 11:44 UTC, golovachev-yaroslav commented on apps/angular/src/app/features/auth/registration/registration.component.ts
> +	selector: 'camp-registration',
To much indents.

2023-08-02 11:44 UTC, golovachev-yaroslav commented on apps/angular/src/app/features/auth/registration/registration.component.ts
> +	/** Form group for login. */
`/** Form group for registration. */` ?

2023-08-02 11:44 UTC, golovachev-yaroslav commented on libs/core/models/login.ts
> +	readonly email: string | null;
Email and password could be nullable?

2023-08-02 12:36 UTC, andrey-gazzaev requested changes

2023-08-02 12:36 UTC, andrey-gazzaev commented on apps/angular/src/app/features/auth/login/login.component.ts
> +		if (error instanceof HttpErrorResponse) {
It's strange to see the UI layer mentioning server, http, etc. As far as I can tell, you have an abstraction leak going on here.

2023-08-02 12:36 UTC, andrey-gazzaev commented on apps/angular/src/app/features/auth/login/login.component.ts
> +					});
What if you have a lot of form fields? Don't you already want to repeat this code for each field?

2023-08-02 12:36 UTC, andrey-gazzaev commented on apps/angular/src/app/features/auth/login/login.component.ts
> +		if (!this.loginForm.invalid) {
Please avoid nested conditions. https://dev.to/yvonnickfrin/devtips-use-early-returns-to-avoid-nested-conditions-4i51
```suggestion 
		if (this.loginForm.invalid) {
		  return;
		}
```

2023-08-02 12:36 UTC, andrey-gazzaev commented on apps/angular/src/app/features/auth/login/login.component.ts
> +					catchError((error: unknown) => this.handleLoginError(error)),
Silencing an error is not the best option. What if you may have several error handlers? For example, one at the domain layer and one at the UI layer?

2023-08-02 12:36 UTC, andrey-gazzaev commented on apps/angular/src/app/features/auth/login/login.component.ts
> +					},
If you had thrown an error in `catchError` you would not have to describe it here

2023-08-03 06:48 UTC, golovachev-yaroslav approved these changes

2023-08-03 06:48 UTC, golovachev-yaroslav commented on libs/core/dtos/token-responce.dto.ts
> +	readonly access: 'string';
Why 'string' ?

2023-08-03 06:48 UTC, golovachev-yaroslav commented on libs/core/dtos/token-responce.dto.ts
> +	readonly access: 'string';
Discussed, resolved.

2023-08-03 07:18 UTC, timofei-maximov-saritasa requested changes

2023-08-03 07:18 UTC, timofei-maximov-saritasa commented on apps/angular/src/core/services/auth.service.ts
> +			.pipe(map(res => this.setTokens(res)));
Let's use `tap` operator here. It's better suited for doing side-effects. 

Usually, we expect that `map` operator transforms our data

2023-08-03 07:18 UTC, timofei-maximov-saritasa commented on apps/angular/src/core/services/auth.service.ts
> +		localStorage.setItem(this.accessTokenName, tokens.access);
Let's create service to work with storage. What if we decide to change `localStorage` to `sessionStorage`?
Also, there are cases when we want to replace `localStorage` with DI to another storage type. For example, SSR or mobile apps. 

Moreover, storage service will give you better types.

If I'm not mistaken we had a few examples in DI lecture.

2023-08-03 07:18 UTC, timofei-maximov-saritasa commented on libs/core/models/login.ts
> +/** Login interface. */
No need for `interface` word here, you are duplicating context, since you already described your login model with `interface`.

2023-08-03 12:09 UTC, andrey-gazzaev commented on apps/angular/src/core/interceptors/refresh-token.interceptor.ts
> +	private isRefreshing = false;
Why do you need `isRefreshing` flag?

2023-08-03 12:09 UTC, andrey-gazzaev commented on apps/angular/src/app/features/auth/shared-components/password-field/password-field.component.ts
> +	@Input() public passwordControl;
```suggestion
	@Input() public passwordControl: FormControl;
```

2023-08-03 12:09 UTC, andrey-gazzaev commented on apps/angular/src/app/features/auth/login/login.component.ts
> +		if (this.loginForm.invalid === false) {
Avoid nested conditions

2023-08-04 05:33 UTC, Emil-Arzumanov commented on apps/angular/src/core/interceptors/refresh-token.interceptor.ts
> +	private isRefreshing = false;
Because interceptor will work endlessly, if some is wrong with token.

2023-08-04 06:06 UTC, Emil-Arzumanov commented on libs/core/utils/snake-to-camel.util.ts
> +}
What if i will add enum of possible attributes for dto and module?

2023-08-04 06:23 UTC, andrey-gazzaev commented on libs/core/utils/snake-to-camel.util.ts
> +}
You still haven't solved the problem. What to do if one field name comes from the server, but another one is used in the project?

2023-08-04 06:23 UTC, andrey-gazzaev commented on apps/angular/src/core/utils/auth-error.util.ts
> +}
`errorCatchDomain` and `errorCatchUI` still do not show the meaning of the functions. How do `Domain` and `UI` relate to the scope of the project? What do these terms describe in relation to these functions?

2023-08-04 06:23 UTC, andrey-gazzaev commented on apps/angular/src/core/interceptors/refresh-token.interceptor.ts
> +				if (error instanceof HttpErrorResponse && error.message.includes('401')) {
The corrector will check the error code, not the message. The `error` object has a `status` field.

2023-08-04 06:23 UTC, andrey-gazzaev commented on libs/core/models/validated-form.ts
> +export type CustomFormGroupType<T extends Record<string, any>> = FormGroup<{ [key in keyof T]: FormControl<T[key]> }>;
Good idea, but let's make the title more clear

2023-08-04 06:23 UTC, andrey-gazzaev commented on libs/core/models/auth-custom-error.ts
> +	public constructor(public readonly mappedErrorArray: AuthErrorType[]) {
```suggestion
/** Authentication custom error. */
export class AuthCustomError extends Error {
	public constructor(public readonly mappedErrorArray: readonly AuthErrorType[]) {
```

2023-08-04 06:23 UTC, andrey-gazzaev commented on apps/angular/src/core/utils/auth-error.util.ts
> +}
This function can be found in the utilities folder

2023-08-07 02:53 UTC, andrey-gazzaev approved these changes

2023-08-07 02:53 UTC, andrey-gazzaev commented on apps/angular/src/app/features/auth/login/login.component.html
> +		<mat-error *ngFor="let error of getFieldErrors(email)">
Don't forget to add `trackBy` for `ngFor`.

2023-08-07 02:53 UTC, andrey-gazzaev commented on libs/core/mappers/registration-error.mapper.ts
> +		});
As far as I understand there is no `first_name` field in your form, but there is a `firstName` field. Let's make a mapper that maps `first_name` to `firstName`.

2023-08-07 02:53 UTC, andrey-gazzaev commented on libs/core/utils/snake-to-camel.util.ts
> +}
As far as I can see, you're not using this code. Let's delete it.

2023-08-07 04:39 UTC, golovachev-yaroslav requested changes

2023-08-07 04:39 UTC, golovachev-yaroslav commented on apps/angular/src/core/utils/auth-error.util.ts
> -export function errorCatchDomain<T>(): OperatorFunction<T, T> {
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#actions
A function shoud start from a verb. 
I think it would be better to call `catchErrorDomain`.

2023-08-07 04:42 UTC, timofei-maximov-saritasa approved these changes

2023-08-07 05:22 UTC, golovachev-yaroslav approved these changes

2023-08-07 07:12 UTC, merged