Feature/jc 556 display details for selected anime
saritasa-nest/camp-js-2023-emil-arzumanov pull request #7
Opened 2023-08-08 06:27 UTC by Emil-Arzumanov

[TASK](https://saritasa.atlassian.net/browse/JC-554)

2023-08-08 08:47 UTC, panov-aleksey-saritasa requested changes

2023-08-08 08:47 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/details/details.component.ts
> +		});
Actually, `open` method of Material dialogs accepts generics, so you can use them to properly type the correct shape of data, which should be passed into dialog.

2023-08-08 08:47 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/details/details.component.ts
> +		});
Unfortunately, `Material` docs does not contain an example of generic usage for dialogs, so if you don't understand how to do it right, you can DM me in slack, I will help you to figure it out :)

2023-08-08 08:47 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/app.module.ts
> +		AuthService,
I guess `AuthService` is provided is root, so you don't need to additionally provide it into module

2023-08-08 08:47 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +		window.location.replace('/anime/table');
Why do you need this? Wouldn't navigation via angular `router` do the job?

2023-08-08 08:47 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +		window.location.replace('/anime/table');
I think I understood your problem, you use a function for checking whether a user is logged in or not. The function is not reactive, its value is not updated automatically whenever a user does log in or log out. So UI is not updated as well.

2023-08-08 08:47 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +		window.location.replace('/anime/table');
As a solution I would recommend you using observables and subjects, they are reactive in the context of Angular. You can remake `isLoggedIn` into subject instead of function (you can use either [BehaviorSubject](https://www.learnrxjs.io/learn-rxjs/subjects/behaviorsubject) or [ReplaySubject](https://www.learnrxjs.io/learn-rxjs/subjects/replaysubject)) and updating its value inside the auth service

2023-08-08 08:47 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/dom-sanitizer.service.ts
> +
```suggestion
	private sanitizer = inject(DomSanitizer);
```

2023-08-08 08:47 UTC, panov-aleksey-saritasa commented on libs/core/dtos/anime-details.dto.ts
> +	readonly trailer_youtube_id: string | null;
Not sure, but isn't docs are required for DTO's properties by eslint?

2023-08-08 08:53 UTC, panov-aleksey-saritasa commented on libs/core/mappers/anime-details.mapper.ts
> +			trailerYoutubeId: dto.trailer_youtube_id ? `${youtubeLink}${dto.trailer_youtube_id}` : null,
What is the purpose of `youtubeLink` param in this method? Isn't it always the same?

2023-08-08 09:57 UTC, Emil-Arzumanov commented on apps/angular/src/app/features/anime/table/table.component.ts
> +		window.location.replace('/anime/table');
I created 'isLoggedIn$' behavior subject only in 'table.component'. Because everywhere else i need 'isLoggedIn' as function that return boolean.

2023-08-09 01:29 UTC, dbitkovski requested changes

2023-08-09 01:29 UTC, dbitkovski commented on apps/angular/src/app/features/anime/details/details.component.ts
> +	private readonly animeId = this.getIdFromParams();
Getting params from the URL like this is totally fine but it's better to use `Router.params` observable instead. There are cases when angular doesn't destroy a component but path params are updated. Your code won't handle it.

2023-08-09 01:29 UTC, dbitkovski commented on apps/angular/src/app/features/anime/details/details.component.html
> +</div>
Create a component for header element. You already have duplicated code in 2 components.

2023-08-09 01:29 UTC, dbitkovski commented on apps/angular/src/app/features/anime/details/details.component.ts
> +	}
Imagine you have several places to log out. For example, you can log out using button in a header and kind of "Settings" page. Now your components have additional informaton about how the application behaves when user logs out. They know that we need to redirect user somewhere and probably do something else. That's not cool because:
- your component has information about things not related to component
- you increase the amount of knoledge all developers must have to write simple "logout" function.

I recommend refactorring this peace of code. I see `AuthService.logout()` method updates the value of `isLoggedInSubject`. Probably, we can use this information in `AppComponent` and let it control the app behaviour when user logs out.

2023-08-09 01:29 UTC, dbitkovski commented on apps/angular/src/app/features/anime/details/poster-popup/poster-popup.component.css
> +@keyframes custom-dialog-enter {
_Not necessary_
Animations are cool, but we should respect people choise about them. If a user doesn't want to see extra motion, we have to listen to them and disable animations.
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

2023-08-09 01:29 UTC, dbitkovski commented on apps/angular/src/app/features/auth/registration/registration.component.html
> +		<button tabindex="-1" type="button" mat-icon-button matSuffix (click)="hidePasswordRetype = !hidePasswordRetype"
Not cool, you can't reach the button from a keyboard now

2023-08-09 01:29 UTC, dbitkovski commented on apps/angular/src/core/services/auth-guard.service.ts
> +					return false;
You can `return this.router.navigate(['/home/login'])`.

2023-08-09 01:29 UTC, dbitkovski commented on apps/angular/src/core/services/auth.service.ts
>  		return true;
```suggestion
		return this.storageService.getValue(this.accessTokenName) !== null && this.storageService.getValue(this.refreshTokenName) !== null
```

2023-08-09 01:29 UTC, dbitkovski commented on apps/angular/src/core/services/dom-sanitizer.service.ts
> +	name: 'safe',
As for components and directives, pipe names should be prefixed with our project name. In your case it will be `campSafe`. It's easier for developers to distinguish which parts of code are from angular lib and which are not

2023-08-09 01:29 UTC, dbitkovski commented on apps/angular/src/core/services/logged-auth-guard.service.ts
> +						return false;
Same here

2023-08-09 01:29 UTC, dbitkovski commented on libs/core/dtos/studio.dto.ts
> +		* Creation date.
There is something wrong with indentation. You need to use `space` but there is a `tab`
![image](https://github.com/saritasa-nest/camp-js-2023-emil-arzumanov/assets/37259001/20d931d4-a511-4e83-b582-0cb7596b350e)
Check all other multiline docs. The problem is the same

2023-08-09 01:29 UTC, dbitkovski commented on libs/core/dtos/studio.dto.ts
> +	readonly name: string;
Missing doc

2023-08-09 07:44 UTC, Emil-Arzumanov commented on apps/angular/src/app/features/anime/details/poster-popup/poster-popup.component.css
> +@keyframes custom-dialog-enter {
This animation was completely unnecessary, i will just delete it.

2023-08-09 08:55 UTC, dbitkovski requested changes

2023-08-09 08:55 UTC, dbitkovski commented on apps/angular/src/app/features/anime/details/details.component.ts
> +export class AnimeDetailsComponent {
Rename files and selector as well

2023-08-09 08:55 UTC, dbitkovski commented on apps/angular/src/app/features/anime/table/table.component.ts
Rename this component as well as you did for AnimeDetails

2023-08-09 09:23 UTC, dbitkovski approved these changes

2023-08-09 11:12 UTC, panov-aleksey-saritasa approved these changes

2023-08-09 11:12 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/auth/registration/registration.component.html
> +		<button tabindex="-1" type="button" mat-icon-button matSuffix (click)="hidePasswordRetype = !hidePasswordRetype"
Seems unfixed, not sure why it was resolved

2023-08-09 11:12 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/interceptors/refresh-token.interceptor.ts
> +					if (elem) {
What do you mean by `elem`? Can we find a more suitable name?

2023-08-09 11:55 UTC, merged