Feature/jc 566 anime item management
saritasa-nest/camp-js-2023-emil-arzumanov pull request #8
Opened 2023-08-15 18:56 UTC by Emil-Arzumanov

[TASK](https://saritasa.atlassian.net/browse/JC-564)

2023-08-16 03:10 UTC, dbitkovski requested changes

2023-08-16 03:10 UTC, dbitkovski commented on apps/angular/src/app/features/anime/components/chips-form-field/chips-form-field.component.ts
> +		this.filteredItems$ = combineLatest([
It's better if you create a function that will return initialization value. It's not required because this function won't be reused but we try to make a constructor function simple and with less code

2023-08-16 10:02 UTC, Emil-Arzumanov commented on apps/angular/src/app/features/anime/anime-managers/anime-form/anime-form.component.ts
> +			airedStart: this.formBuilder.control<Date | null>(null),
I wrote you about it in slack

2023-08-17 00:28 UTC, dbitkovski requested changes

2023-08-17 00:28 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-managers/anime-form/anime-form.component.ts
> +	public submitType: SubmitType | null = null;
Okay, it's much better than having any string but actually I meant to use boolean value 🐱 
I can't come up with a case when form might be in 3 different states. It's always either for creation or edit. So you can simply make `@Input() isEdit: boolean = false` property

2023-08-17 00:28 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-managers/anime-form/anime-form.component.ts
> +		}
Please, don't forget `take(1)` or `first()` for streams when you need to get result only once. Even if you have a knoledge that `editAnime` emits only once, the `anime-form.component` doesn't (and shouldn't) know about that.
So to make it more safe it's better to apply operators I mentioned above

2023-08-17 00:28 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-managers/anime-form/anime-form.component.ts
> +		* @param searchControl Search request parameters.
Indent issue

2023-08-17 00:28 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-managers/anime-form/anime-form.component.ts
> +	protected getStudios(pagination: PaginationParams, searchControl: string | null): Observable<Pagination<Studio>> {
We usually add `control` suffix when a property contains `FormControl` object or DOM element like `input`, `select`, etc. They're actual controls.
Here I see that it's just a searching value

2023-08-17 00:28 UTC, dbitkovski commented on apps/angular/src/app/features/anime/components/chips-form-field/chips-form-field.component.css
> +span {
I don't see `span` in your template. Also, there is no `ViewEncapsulation.None` to make styles global

2023-08-17 00:28 UTC, dbitkovski commented on apps/angular/src/app/features/anime/components/confirm-delete/confirm-delete.component.html
> +<button type="button" mat-raised-button color="primary" (click)="dialogRef.close()">Cancel</button>
You can use `mat-dialog-close` directive instead of manual call of `dialogRef.close()`

2023-08-17 00:28 UTC, dbitkovski commented on apps/angular/src/app/features/anime/components/confirm-delete/confirm-delete.component.ts
> +	}
I would recommend refactoring this method. From my perspective, the dialog shouldn't call `this.animeService.deleteAnimeById` but only returns `true` or `false`.
Parent component subscribes `afterClosed` observable. If dialog is closed with `true` value, than it calls the service method and redirect to another page. Otherwise, it does nothing.
This approach provides several benefits:
- if you open the dialog from different places you might handle the result differently. It's helpful when you don't want to redirect a user to `/anime/table` for some reason
- since the component is called `ConfirmDelete`, we really make it a confirmation dialog so we stick to SRP
- usually, we reuse such dialogs for all places when we need user's confirmation. We pass custom message so we don't need to create a new component for new use case (you don't need to do that right now, just for your information)

2023-08-17 00:28 UTC, dbitkovski commented on apps/angular/src/app/features/anime/components/image-manager/image-manager.component.ts
> +			});
We shouldn't interact with s3 from here. The logic is pretty the same as for confirmation dialog. `ImageManager` is required to choose an image. Call `this.s3directService.getS3DirectParams` on form submit and set error if image is incorrect

2023-08-17 00:28 UTC, dbitkovski commented on apps/angular/src/core/services/anime.service.ts
> +	}
I believe it's better to create `StudiosService` class and move it there. `AnimeService` knows to much about the entities which are not anime

2023-08-17 00:28 UTC, dbitkovski commented on apps/angular/src/core/services/anime.service.ts
> +	}
Same here, `GenresService` will be fine

2023-08-17 06:36 UTC, Emil-Arzumanov commented on apps/angular/src/app/features/anime/components/confirm-delete/confirm-delete.component.html
> +<button type="button" mat-raised-button color="primary" (click)="dialogRef.close()">Cancel</button>
I think it doesn't work with 'cdk/dialog'

2023-08-18 01:42 UTC, dbitkovski approved these changes

2023-08-18 01:42 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-details/anime-details.component.ts
> +		).subscribe();
If you need to subscribe to another stream from operators, you can use `switchMap` instead. There are bunch of flatten operators, I recommend you reading about them we use them a lot https://habr.com/ru/articles/715882/

2023-08-18 01:42 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-managers/anime-form/anime-form.component.ts
> +	private submitDetails(): void {
It's better to return `Observable<void>` and subscribe to a stream in `onSubmit` method

2023-08-18 01:42 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-managers/anime-form/anime-form.component.ts
> +import { ValidatedFormGroupType } from '@js-camp/core/models/validated-form';
Move this type from `libs/core` to `apps/angular/src`. This is angular-specific type we musn't put it to core library

2023-08-18 16:44 UTC, merged